name: pepbench
channels:
  - defaults
  - nvidia
  - conda-forge
dependencies:
  - python=3.10.0
  - pip=25.1
  - setuptools=78.1.1
  - wheel=0.45.1
  - ca-certificates=2025.2.25
  - openssl=1.1.1w
  - libffi=3.3
  - zlib=1.2.13
  - xz=5.6.4
  - bzip2=1.0.8
  - ncurses=6.4
  - readline=8.2
  - sqlite=3.50.2
  - tk=8.6.14
  - libuuid=1.41.5
  - libxcb=1.17.0
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - pthread-stubs=0.3
  - libstdcxx-ng=11.2.0
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - ld_impl_linux-64=2.40
  - pip:
      - annotated-types==0.7.0
      - certifi==2025.7.14
      - charset-normalizer==3.4.2
      - click==8.2.1
      - filelock==3.13.1
      - fsspec==2024.6.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - hf-xet==1.1.5
      - huggingface-hub==0.33.4
      - idna==3.10
      - jinja2==3.1.4
      - joblib==1.5.1
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - networkx==3.3
      - numpy==1.25.2
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu11==8.7.0.84
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu11==2.19.3
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.9
      - nvidia-nvtx-cu11==11.8.86
      - nvidia-nvtx-cu12==12.8.90
      - packaging==25.0
      - pandas==1.5.3
      - peptidy==0.0.1
      - pillow==11.0.0
      - platformdirs==4.3.8
      - protobuf==6.31.1
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - python-dateutil==2.9.0.post0
      - pytorch-triton==3.4.0+git11ec6354
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.4
      - safetensors==0.5.3
      - scikit-learn==1.2.2
      - scipy==1.15.3
      - sentry-sdk==2.33.2
      - six==1.17.0
      - smmap==5.0.2
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tokenizers==0.19.1
      - torch==2.9.0.dev20250720+cu128
      - torchaudio==2.8.0.dev20250720+cu128
      - torchvision==0.24.0.dev20250720+cu128
      - tqdm==4.67.1
      - transformers==4.41.2
      - triton==2.2.0
      - typing-extensions==4.12.2
      - typing-inspection==0.4.1
      - urllib3==2.5.0
      - wandb==0.21.0
      - xgboost==2.0.3
